### PR TITLE
[IMP] saas~17.3: remove doall/numbercall from ir_cron

### PR DESCRIPTION
**Pull request by fdamhaut**
- Remove multiple calls and number of calls mechanism.

COM: odoo/odoo#151628
ENT: odoo/enterprise#58157
UP: https://github.com/odoo/upgrade/pull/5786
task-id: 3687442

### CODE REVIEW

**Comment by cawo-odoo** [comment]
Please add https://github.com/odoo/upgrade/pull/5786 to the references in the commit message

**Review by cawo-odoo — APPROVED** [review]
LGTM

**Comment by rco-odoo** [comment]
@cawo-odoo both community and enterprise branches have been r+.
The runbot should be green, we are simply waiting for it to complete.

**Comment by cawo-odoo** [comment]
@KangOl community PRs are ready, this should be good to go?

**Comment by KangOl** [comment]
@robodoo rebase-ff r+

**Comment by d-fence** [comment]
robodoo retry
(failing test diasabled on runbot)

**Comment by Julien00859** [comment]
image

**Comment by aj-fuentes** [comment]
@robodoo r+

**Pull request closed without merging**
