### PR TITLE
[chore] format code using ruff instead of black 

### PR DESCRIPTION
**Pull request by KangOl**

### CODE REVIEW

**Review by aj-fuentes — APPROVED** [review]
LGTM, the comment could be ignored.

**Comment by KangOl** [comment]
Question:
Do we keep the `[tools.black]` section in the `pyproject.toml` file?
It is used by the `tools/generate-inherit.py` script.
Options:
 - keep it
 - change the script to either use the value from `[tools.ruff]` or hardcode the line-length.
 - We can also not format the output of the script ourself and let `ruff` doing it via `pre-commit`.

**Comment by aj-fuentes** [comment]
> We can also not format the output of the script ourself and let ruff doing it via pre-commit.

I think that's the best option. As you said, regenerate the script then let pre-commit reformat it. I'd prefer to decouple the generating script from the linting.

**Comment by KangOl** [comment]
upgradeci retry with always only base

**Comment by KangOl** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
