### PR TITLE
[FIX] util/records: correct query construction

### PR DESCRIPTION
**Pull request by aj-fuentes**
Check that there are unique columns to expand the extra conditions.

### CODE REVIEW

**Comment by KangOl** [comment]
What about simply
```diff
-                    % {"ands": "AND".join('"%s"=t."%s"' % (col, col) for col in uniq_cols)}
+                    % {"ands": "AND".join('"%s"=t."%s"' % (col, col) for col in uniq_cols) or "true"}

**Comment by aj-fuentes** [comment]
Checking the other error...

**Comment by aj-fuentes** [comment]
@KangOl this looks good, only error is in pos_blackbox

**Comment by KangOl** [comment]
@robodoo r+

**Pull request closed without merging**
